# Generated by Django 3.2.5 on 2021-07-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='URLs',
        ),
    ]
